SELECT 
    track_id, artist_s_name,
    CASE 
        WHEN LOWER(artist_s_name) LIKE '%adele%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%agust d%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%a-ha%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%ak4:20%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%alvaro diaz%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%anitta%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%arcangel%' THEN 'Reggaeton'
        WHEN LOWER(artist_s_name) LIKE '%ariana grande%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%arctic monkeys%' THEN 'Rock'
        WHEN LOWER(artist_s_name) LIKE '%avicii%' THEN 'Electrónica'
        WHEN LOWER(artist_s_name) LIKE '%beyoncé%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%billie eilish%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%bizarrap%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%blackpink%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%bruno mars%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%bts%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%burna boy%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%camila cabello%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%charlie puth%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%chase atlantic%' THEN 'Rock'
        WHEN LOWER(artist_s_name) LIKE '%chencho corleone%' THEN 'Reggaeton'
        WHEN LOWER(artist_s_name) LIKE '%chino pacas%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%christian nodal%' THEN 'Regional Mexicano'
        WHEN LOWER(artist_s_name) LIKE '%coldplay%' THEN 'Rock'
        WHEN LOWER(artist_s_name) LIKE '%daddy yankee%' THEN 'Reggaeton'
        WHEN LOWER(artist_s_name) LIKE '%david guetta%' THEN 'Electrónica'
        WHEN LOWER(artist_s_name) LIKE '%demi lovato%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%dj lacy%' THEN 'Electrónica'
        WHEN LOWER(artist_s_name) LIKE '%dj snake%' THEN 'Electrónica'
        WHEN LOWER(artist_s_name) LIKE '%doja cat%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%drake%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%dua lipa%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%duncan laurence%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%duki%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%ed sheeran%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%elton john%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%eminem%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%farruko%' THEN 'Reggaeton'
        WHEN LOWER(artist_s_name) LIKE '%feid%' THEN 'Reggaeton'
        WHEN LOWER(artist_s_name) LIKE '%frank ocean%' THEN 'R&B'
        WHEN LOWER(artist_s_name) LIKE '%future%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%guns n\' roses%' THEN 'Rock'
        WHEN LOWER(artist_s_name) LIKE '%halsey%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%harry styles%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%imagine dragons%' THEN 'Rock'
        WHEN LOWER(artist_s_name) LIKE '%j balvin%' THEN 'Reggaeton'
        WHEN LOWER(artist_s_name) LIKE '%jason derulo%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%jessica darrow%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%john legend%' THEN 'R&B'
        WHEN LOWER(artist_s_name) LIKE '%juice wrld%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%justin bieber%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%kali uchis%' THEN 'R&B'
        WHEN LOWER(artist_s_name) LIKE '%kanye west%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%karol g%' THEN 'Reggaeton'
        WHEN LOWER(artist_s_name) LIKE '%katy perry%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%keane%' THEN 'Rock'
        WHEN LOWER(artist_s_name) LIKE '%kendrick lamar%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%lady gaga%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%lana del rey%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%lil baby%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%lil nas x%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%lizzo%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%lorde%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%maluma%' THEN 'Reggaeton'
        WHEN LOWER(artist_s_name) LIKE '%marshmello%' THEN 'Electrónica'
        WHEN LOWER(artist_s_name) LIKE '%maroon 5%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%megan thee stallion%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%michael bublé%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%miguel%' THEN 'R&B'
        WHEN LOWER(artist_s_name) LIKE '%miley cyrus%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%morat%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%natti natasha%' THEN 'Reggaeton'
        WHEN LOWER(artist_s_name) LIKE '%nelly furtado%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%nicki minaj%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%nirvana%' THEN 'Rock'
        WHEN LOWER(artist_s_name) LIKE '%olivia rodrigo%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%ozuna%' THEN 'Reggaeton'
        WHEN LOWER(artist_s_name) LIKE '%paloma mami%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%paulo londra%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%pharrell williams%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%pitbull%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%playboi carti%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%post malone%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%queen%' THEN 'Rock'
        WHEN LOWER(artist_s_name) LIKE '%rihanna%' THEN 'R&B'
        WHEN LOWER(artist_s_name) LIKE '%rosalía%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%rosalía%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%sam smith%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%sebastian yatra%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%selena gomez%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%shakira%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%sia%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%snoop dogg%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%taylor swift%' THEN 'Pop'
        WHEN LOWER(artist_s_name) LIKE '%the beatles%' THEN 'Rock'
        WHEN LOWER(artist_s_name) LIKE '%the chainsmokers%' THEN 'Electrónica'
        WHEN LOWER(artist_s_name) LIKE '%the killers%' THEN 'Rock'
        WHEN LOWER(artist_s_name) LIKE '%the neigbourhood%' THEN 'Rock'
        WHEN LOWER(artist_s_name) LIKE '%the weeknd%' THEN 'R&B'
        WHEN LOWER(artist_s_name) LIKE '%tiësto%' THEN 'Electrónica'
        WHEN LOWER(artist_s_name) LIKE '%travis scott%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%twenty one pilots%' THEN 'Rock'
        WHEN LOWER(artist_s_name) LIKE '%tyler, the creator%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%u2%' THEN 'Rock'
        WHEN LOWER(artist_s_name) LIKE '%wiz khalifa%' THEN 'Hip Hop/Rap'
        WHEN LOWER(artist_s_name) LIKE '%yandel%' THEN 'Reggaeton'
        WHEN LOWER(artist_s_name) LIKE '%zayn%' THEN 'Pop'
        ELSE 'Otros'
    END AS genero_artista
FROM 
    `laboratoria2.datos_hipotesis.views_s_c`

ORDER BY 
    artist_s_name
